trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

pr:
- master

pool:
  vmImage: ubuntu-latest

parameters:
  - name: deploy
    displayName: Deploy
    type: boolean
    default: false

jobs:
- job: continuous_integration
  displayName: Continuous Integration
  steps:
  - task: NodeTool@0
    displayName: Install Node
    inputs:
      versionSpec: '12.x'
  - bash: npm install --global yarn
    displayName: Install Yarn
  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
  - bash: yarn && yarn && yarn test
    displayName: Compile and test extension
    env:
      DISPLAY: ':99.0'

- job: deploy_to_market
  displayName: Deploy to extension marketplace
  condition: and(succeeded(), eq(${{ parameters.deploy }}, 'true'))
  dependsOn: continuous_integration
  steps:
  - bash:
      echo '$(Build.SourceBranchName)' | sed 's/v\(.\+\)/\1/' |
      sed -i s/::release-version::/$(</dev/stdin)/ package.json &&
      yarn &&
      yarn deploy
    env:
      VSCE_PAT: $(VSCE_PAT)
